
    create table categories (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table order_items (
        quantity integer not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        primary key (id)
    );

    create table orders (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        status varchar(255) not null,
        primary key (id)
    );

    create table products (
        price float(53) not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        description varchar(1000),
        name varchar(255) not null,
        primary key (id)
    );

    create table users (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        email varchar(255) not null unique,
        name varchar(255),
        password varchar(255) not null,
        primary key (id)
    );

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;
